USER-SUPPLIED VALUES:
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/usememos/memos
  tag: 0.24.0
ingress:
  main:
    enabled: false
mariadb:
  auth:
    database: memos
    password: changeme
    rootPassword: changeme
    username: memos
  enabled: false
  primary:
    persistence:
      enabled: false
persistence:
  data:
    enabled: true
    mountPath: /var/opt/memos
    retain: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClassName: ""
podSecurityContext:
  fsGroup: 65534
  runAsGroup: 65534
  runAsUser: 65534
postgresql:
  auth:
    database: memos
    postgresPassword: changeme
  enabled: false
  primary:
    persistence:
      enabled: false
service:
  main:
    type: NodePort
    ports:
      http:
        port: 5230
        nodePort: 32080
